name: FAMT Build

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build FAMT Windows x64
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Check
        run: cargo check --all-targets

      - name: Test
        run: cargo test --all-targets

      - name: Build Release
        run: cargo build --release

      - name: Upload Windows executable
        uses: actions/upload-artifact@v4
        with:
          name: famt-windows-x64
          path: target/release/famt.exe
